version: '2'
services:
    db:
        image: postgres:15
        volumes:
            - sample_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    app:
        build: .
        ports:
            - 8080:8080
        environment:
            spring.datasource.url: "jdbc:postgresql://db:5432/sample"

volumes:
    sample_db: {}